import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { Transaction } from "@/src/types/transaction";

Font.register({
  family: "Helvetica",
  fonts: [],
});

const CYAN = "#22d3ee";
const DARK = "#111827";
const GRAY = "#6b7280";
const LIGHT_GRAY = "#f3f4f6";
const RED = "#ef4444";
const GREEN = "#10b981";
const WHITE = "#ffffff";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    color: DARK,
    backgroundColor: WHITE,
    paddingBottom: 40,
  },
  header: {
    backgroundColor: DARK,
    paddingHorizontal: 32,
    paddingVertical: 20,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: CYAN,
    letterSpacing: 1,
  },
  headerSub: {
    fontSize: 10,
    color: "#9ca3af",
    marginTop: 3,
  },
  body: {
    paddingHorizontal: 32,
    paddingTop: 24,
  },
  sectionTitle: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: GRAY,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 24,
  },
  statBox: {
    flex: 1,
    backgroundColor: LIGHT_GRAY,
    borderRadius: 6,
    padding: 12,
  },
  statLabel: {
    fontSize: 8,
    color: GRAY,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
  },
  red: { color: RED },
  green: { color: GREEN },
  dark: { color: DARK },
  table: {
    width: "100%",
    marginBottom: 24,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: DARK,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    marginBottom: 2,
  },
  tableHeaderCell: {
    color: WHITE,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
  },
  tableRow: {
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 3,
  },
  tableRowAlt: {
    backgroundColor: LIGHT_GRAY,
  },
  cell: {
    fontSize: 8,
    color: DARK,
  },
  colDate: { width: "13%" },
  colDesc: { width: "37%" },
  colCat: { width: "22%" },
  colType: { width: "12%" },
  colAmount: { width: "16%", textAlign: "right" },
  footer: {
    position: "absolute",
    bottom: 16,
    left: 32,
    right: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 6,
  },
  footerText: {
    fontSize: 7,
    color: GRAY,
  },
  divider: {
    height: 1,
    backgroundColor: "#e5e7eb",
    marginBottom: 20,
  },
  catRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  catDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CYAN,
    marginRight: 8,
  },
  catName: { flex: 1, fontSize: 8 },
  catAmt: { fontSize: 8, fontFamily: "Helvetica-Bold" },
  catPct: { fontSize: 7, color: GRAY, width: 36, textAlign: "right" },
  barBg: {
    height: 4,
    backgroundColor: "#e5e7eb",
    borderRadius: 2,
    marginTop: 2,
    marginBottom: 4,
  },
  barFill: {
    height: 4,
    backgroundColor: CYAN,
    borderRadius: 2,
  },
});

function fmt(amount: number, showSign = false): string {
  const abs = Math.abs(amount).toFixed(2);
  if (showSign) return amount < 0 ? `-$${abs}` : `+$${abs}`;
  return `$${abs}`;
}

function Footer({ month }: { month: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>
        Generated by ExpenseAI • expenseai.com
      </Text>
      <Text style={styles.footerText}>{month}</Text>
      <Text
        style={styles.footerText}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

type CategoryEntry = { category: string; amount: number; percentage: number };

type Props = {
  month: string;
  monthLabel: string;
  totalSpent: number;
  totalIncome: number;
  net: number;
  categoryData: CategoryEntry[];
  transactions: Transaction[];
};

export default function MonthlyReport({
  monthLabel,
  totalSpent,
  totalIncome,
  net,
  categoryData,
  transactions,
}: Props) {
  return (
    <Document>
      {/* Page 1: Summary */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>ExpenseAI</Text>
          <Text style={styles.headerSub}>Monthly Report — {monthLabel}</Text>
        </View>

        <View style={styles.body}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <View style={styles.statsRow}>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>Total Spent</Text>
              <Text style={[styles.statValue, styles.red]}>
                {fmt(totalSpent)}
              </Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>Total Income</Text>
              <Text style={[styles.statValue, styles.green]}>
                {fmt(totalIncome)}
              </Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>Net</Text>
              <Text
                style={[styles.statValue, net >= 0 ? styles.green : styles.red]}
              >
                {fmt(net, true)}
              </Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>Transactions</Text>
              <Text style={[styles.statValue, styles.dark]}>
                {transactions.length}
              </Text>
            </View>
          </View>

          <View style={styles.divider} />

          <Text style={styles.sectionTitle}>Spending by Category</Text>
          {categoryData.length === 0 ? (
            <Text style={[styles.cell, { color: GRAY }]}>
              No expenses this month.
            </Text>
          ) : (
            categoryData.map((c) => (
              <View key={c.category}>
                <View style={styles.catRow}>
                  <View style={styles.catDot} />
                  <Text style={styles.catName}>{c.category}</Text>
                  <Text style={styles.catPct}>{c.percentage.toFixed(1)}%</Text>
                  <Text style={[styles.catAmt, { width: 60, textAlign: "right" }]}>
                    {fmt(c.amount)}
                  </Text>
                </View>
                <View style={styles.barBg}>
                  <View style={[styles.barFill, { width: `${c.percentage}%` }]} />
                </View>
              </View>
            ))
          )}
        </View>

        <Footer month={monthLabel} />
      </Page>

      {/* Page 2: Transactions */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>ExpenseAI</Text>
          <Text style={styles.headerSub}>
            Transactions — {monthLabel}
          </Text>
        </View>

        <View style={styles.body}>
          <Text style={styles.sectionTitle}>
            All Transactions ({transactions.length})
          </Text>

          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderCell, styles.colDate]}>Date</Text>
              <Text style={[styles.tableHeaderCell, styles.colDesc]}>Description</Text>
              <Text style={[styles.tableHeaderCell, styles.colCat]}>Category</Text>
              <Text style={[styles.tableHeaderCell, styles.colType]}>Type</Text>
              <Text style={[styles.tableHeaderCell, styles.colAmount]}>Amount</Text>
            </View>

            {transactions.map((t, i) => (
              <View
                key={t.id}
                style={[styles.tableRow, i % 2 === 1 ? styles.tableRowAlt : {}]}
                wrap={false}
              >
                <Text style={[styles.cell, styles.colDate]}>{t.date}</Text>
                <Text style={[styles.cell, styles.colDesc]}>
                  {(t.description || "—").slice(0, 45)}
                </Text>
                <Text style={[styles.cell, styles.colCat]}>{t.category}</Text>
                <Text style={[styles.cell, styles.colType, { color: GRAY }]}>
                  {t.type}
                </Text>
                <Text
                  style={[
                    styles.cell,
                    styles.colAmount,
                    t.type === "expense" ? styles.red : styles.green,
                  ]}
                >
                  {t.type === "expense" ? "-" : "+"}
                  {fmt(Number(t.amount))}
                </Text>
              </View>
            ))}
          </View>
        </View>

        <Footer month={monthLabel} />
      </Page>
    </Document>
  );
}
